from playwright.sync_api import sync_playwright
import os
BASE=os.environ.get('APP_TEST_URL','http://localhost:8015')
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox']);page=b.new_page(viewport={'width':1440,'height':1000});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.goto(BASE+'/apps/financial-reset/');page.locator('#demo-scenario').select_option('family');page.locator('#demo').click();page.wait_for_timeout(600);assert page.locator('#reset-plan > .plan-action').count()==3;assert page.locator('#reset-plan > .plan-action[open]').count()==0;assert page.locator('#report-details > details[open]').count()==0;assert page.locator('#next-action').is_visible();assert page.locator('#report .guidance-grid').count()==0;before=page.locator('#next-action strong').inner_text();page.locator('#open-next-action').click();opened=page.locator('.plan-action[open]');assert opened.count()==1;opened.locator('[data-key=status]').select_option('done');assert page.locator('#next-action strong').inner_text()!=before
 # Supporting sections remain usable and exports include closed content.
 annual=page.locator('.report-accordion').filter(has=page.locator('.annual-offer'));annual.locator('summary').first.click();assert page.locator('[data-annual-quote]').first.is_visible();page.locator('[data-annual-quote]').first.fill('300');assert 'Annual quote: $300.00' in page.locator('.annual-result').first.inner_text();annual.locator('summary').first.click()
 matrix=page.locator('.report-accordion').filter(has=page.locator('.expense-pillars'));matrix.locator('summary').first.click();assert page.locator('.expense-pillars').is_visible();matrix.locator('summary').first.click()
 with page.expect_download() as info:page.locator('#download-report').click()
 info.value.save_as('/tmp/dashboard-full-report.txt');text=open('/tmp/dashboard-full-report.txt').read();assert 'Every expense, four saving pillars' in text;assert 'RRSP deductions alongside CCB' in text;assert 'Annual quote: $300.00' in text;assert page.locator('#report-details > details[open]').count()==0
 page.evaluate("window.dispatchEvent(new Event('beforeprint'))");assert page.locator('#report details:not([open])').count()==0;page.evaluate("window.dispatchEvent(new Event('afterprint'))");assert page.locator('#report-details > details[open]').count()==0
 page.locator('#profile-children').select_option('no');assert page.locator('#report-stale').is_visible();assert page.locator('#save-plan').is_disabled();page.locator('#analyze').click();alltext=page.evaluate("ResetDashboard.withExpanded(()=>document.querySelector('#report').innerText)");assert 'Confirm the CCB household mismatch' in alltext;page.set_viewport_size({'width':390,'height':844});assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.locator('#report').scroll_into_view_if_needed();page.screenshot(path='/tmp/dashboard-mobile.png');page.set_viewport_size({'width':1440,'height':1000});page.locator('.report-header').scroll_into_view_if_needed();page.screenshot(path='/tmp/dashboard-desktop.png');assert not errors,errors;b.close();print('Three priorities, next-action advance, expandable evidence, annual quote, complete export/print, stale checks and mobile passed')
