from playwright.sync_api import sync_playwright
import os,json
BASE=os.environ.get('APP_TEST_URL','http://localhost:8011')
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',args=['--no-sandbox']);page=b.new_page(viewport={'width':1440,'height':1000});errors=[];requests=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url));page.add_init_script("Storage.prototype.setItem=function(){throw Error('Storage disabled')};Storage.prototype.getItem=function(){throw Error('Storage disabled')};");page.goto(BASE+'/apps/financial-reset/');page.locator('#demo-scenario').select_option('family');page.locator('#demo').click();text=page.locator('#report').inner_text();assert 'CCB suggests a household with children' in text;assert 'Review RRSP deductions alongside CCB and GST/HST' in text;assert 'Collect medical receipts and insurance records' in text;assert 'Reconcile RRSP contribution receipts' in text;assert page.locator('#reset-plan .plan-action').count()>6
 page.locator('#profile-children').select_option('no');page.locator('#analyze').click();assert 'Confirm the CCB household mismatch' in page.locator('#report').inner_text();assert 'Review RRSP deductions alongside CCB and GST/HST' not in page.locator('#report').inner_text();page.locator('#profile-children').select_option('yes');page.locator('#profile-province').select_option('Alberta');page.locator('#profile-rrspRoom').fill('5000');page.locator('#analyze').click();assert '5000.00 CAD' in page.locator('#report').inner_text()
 page.locator('[data-plan="medical-records"][data-key="status"]').select_option('done');page.locator('[data-plan="medical-records"][data-key="due"]').fill('2026-10-15');page.locator('[data-plan="medical-records"][data-key="notes"]').fill('Requested itemized receipts');page.locator('[data-plan="medical-records"][data-key="impact"]').fill('10');assert 'marked done' in page.locator('#plan-progress').inner_text()
 with page.expect_download() as info:page.locator('#save-plan').click()
 info.value.save_as('/tmp/reset-plan-test.json');snap=json.load(open('/tmp/reset-plan-test.json'));assert snap['format']=='horse-cart-reset-plan';assert 'active' not in snap;assert next(a for a in snap['actions'] if a['id']=='medical-records')['status']=='done'
 data=page.evaluate('ResetDemo.create("family")');page.reload()
 for account in ['card','chequing']:
  csv=data[account].replace('2026-07','2026-10').replace('2026-08','2026-11').replace('2026-09','2026-12').replace('GROCERY MARKET,240','GROCERY MARKET,200');page.locator('#'+account+'-file').set_input_files({'name':account+'.csv','mimeType':'text/csv','buffer':csv.encode()})
 page.locator('#import').click();page.locator('#search').fill('SAVINGS TRANSFER');
 for select in page.locator('[data-category]').all():select.select_option('Transfer / card payment')
 page.locator('#search').fill('');page.locator('#plan-file').set_input_files('/tmp/reset-plan-test.json');page.wait_for_function("document.querySelector('#plan-load-status').textContent.includes('Plan loaded')");page.locator('#coverage').check();page.locator('#cad-confirmed').check();page.locator('#start-date').fill('2026-10-01');page.locator('#end-date').fill('2026-12-31');page.locator('#analyze').click();assert page.locator('#report').is_visible();assert page.locator('[data-plan="medical-records"][data-key="status"]').input_value()=='done';assert page.locator('[data-plan="medical-records"][data-key="notes"]').input_value()=='Requested itemized receipts';assert 'Compare with 2026-07-01 to 2026-09-30' in page.locator('#reset-plan').inner_text();assert '39.70' in page.locator('#reset-plan').inner_text();page.locator('#essentials').fill('3500');assert page.locator('#save-plan').is_disabled();page.locator('#analyze').click();assert page.locator('[data-plan="medical-records"][data-key="status"]').input_value()=='done';page.locator('#plan-file').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':b'{"version":999}'});page.wait_for_function("document.querySelector('#plan-load-status').textContent.includes('Plan not loaded')");assert page.locator('[data-plan="medical-records"][data-key="status"]').input_value()=='done';page.set_viewport_size({'width':390,'height':844});assert page.evaluate('document.documentElement.scrollWidth<=innerWidth');page.screenshot(path='/tmp/reset-plan-mobile.png');assert not errors,errors;assert all(url.startswith(BASE) for url in requests),requests;b.close();print('CCB/RRSP insights, household overrides, saved actions, next-quarter comparison, malformed plan, blocked storage and mobile passed')
