/* Evidence-linked educational guidance. No service calls or invented eligibility. */
(function(root){'use strict';
const pillars=['Remove leakages','Reduce living costs','Benefits & free support','Mindset & strategies'];
const actions={
'Education & training':['Check duplicate fees and unused course subscriptions.','Compare programs by total cost, quality and realistic outcomes.','Check eligible tuition tax credits, scholarships and employer training support; retain official tax slips.','Verify earning opportunities and completion requirements before paying.'],
'Childcare':['Check invoices, subsidies already applied and billing errors.','Compare suitable care options without compromising safety or quality.','Check childcare subsidies and possible Canadian childcare-expense deductions; household circumstances and rules determine eligibility.','Plan care costs alongside work schedules and reliable household support.'],
'Insurance':['Check duplicated coverage, unexplained premiums and policies you no longer need.','Compare equivalent coverage, deductibles and exclusions before switching.','Check employer benefits and public coverage; do not assume premiums qualify for tax relief.','Review dependants, risks, beneficiaries and replacement coverage before cancelling a policy.'],
'Housing':['Check duplicate rent, unexplained charges and insurance overlap.','Compare total housing costs; review renewal terms and practical sharing or relocation options.','Check local housing assistance and any province-specific renter support.','Set an affordable housing limit before committing; compare ownership and rental costs over your time horizon.'],
'Groceries':['Check waste, delivery fees and unused food.','Compare unit prices, plan meals and use lower-cost stores.','Check food support, community kitchens and eligible household benefits.','Shop with a list; distinguish useful savings from bulk purchases that go unused.'],
'Transport':['Check unused parking, duplicate insurance and avoidable penalties.','Compare transit, carpooling and repair costs against financing and running a car.','Check employer transport support and local subsidized transit eligibility.','Calculate the full annual ownership cost before upgrading.'],
'Utilities':['Check billing errors, unused add-ons and overlapping plans.','Compare phone/internet rates and reduce avoidable energy use.','Check local utility relief, energy rebates and low-income programs.','Schedule renewal reminders and negotiate before promotional pricing ends.'],
'Health & care':['Check incorrect billing and insurance reimbursements before accepting the final cost.','Ask about covered services or suitable lower-cost options; preserve necessary care.','Check eligible medical-expense tax credits, employer insurance and provincial coverage. Keep receipts; subtract reimbursements.','Plan for recurring care costs and collect annual pharmacy/clinic statements.'],
'Subscriptions':['Cancel unwanted or duplicate memberships after checking terms.','Compare plans and legitimate household bundles.','Check library access, community recreation and employer-covered services.','Set a renewal calendar and a subscription limit; keep services you value.'],
'Dining & shopping':['Review duplicate purchases, returns, delivery fees and unwanted recurring orders.','Compare practical alternatives, meal preparation and repairs.','Check community resources and eligible employer discounts.','Annualize one recurring habit and use a waiting period for discretionary purchases.'],
'Bank fees':['Ask the bank to explain fees and review payment timing; request a correction where appropriate.','Compare lower-cost accounts against their conditions.','Check eligibility for student, senior or other fee waivers.','Use low-balance alerts without keeping unaffordable minimum balances.'],
'Financing charges':['Verify APR, late charges and whether interest is being charged despite payments.','Compare repayment options and total costs, including transfer fees and promotional expiry.','Check nonprofit credit counselling and eligible hardship support.','Keep minimum payments current; avoid new expensive borrowing and build a manageable repayment plan.'],
'Debt payments':['Separate principal, interest and fees; verify the outstanding balance.','Review repayment terms, penalties and lower-cost alternatives before refinancing.','Check eligible repayment assistance and reputable nonprofit counselling.','Prioritize debts with verified rates, while protecting essentials and a cash buffer.'],
'Giving':['Check recurring commitments and missing donation receipts.','Choose a giving amount that fits current obligations.','Check registered-charity receipts and charitable donation tax-credit eligibility.','Balance generosity, social value and household resilience.'],
'Other':['Resolve merchant identity, refunds and transfers before treating these as spending.','Compare costs only after identifying what the transactions represent.','Eligibility depends on the actual expense; classify it first.','Keep receipts and improve categories for next month’s report.']};
function spiral(s,c){
 const uncertain=!!(s.unknown.length||s.otherCredits||s.duplicates.length||s.unrecognized.length||s.expenses<0);
 const direction=s.surplus<0?'downward':s.surplus>0?'upward':'balanced';
 const label=(uncertain?'Provisional · ':'')+(direction==='downward'?'Downward money-spiral signal':direction==='upward'?'Upward cash-flow signal':'Balanced cash-flow signal');
 const reasons=[`Confirmed income ${s.income.toFixed(2)} CAD minus net spending ${s.expenses.toFixed(2)} CAD = ${s.surplus.toFixed(2)} CAD over this window.`];
 if(uncertain)reasons.push('Unresolved classifications, credits, possible duplicates or unfamiliar charges may change the result.');
 const debtPressure=(s.totals['Financing charges']||0)>0||c.debts.some(d=>d.balance>0&&d.rate!==null&&d.rate>=c.threshold);
 const target=c.essentials===null?null:c.essentials*c.months;
 const reserve=target===null||c.reserve===null||!(c.essentials>0)?'unknown':c.reserve<target?'below target':'target covered';
 let meaning=direction==='downward'?'In this period, spending exceeded confirmed income. If repeated, this can deplete savings or add borrowing. Start by resolving the data and creating breathing room.':direction==='upward'?'In this period, confirmed income exceeded spending. This is a useful starting signal; debt, reserve adequacy and repeatability determine whether the broader situation is improving.':'In this period, spending matched confirmed income. There is no observed margin for new savings; examine resilience and irregular costs.';
 if(debtPressure)meaning+=' Financing charges or entered expensive debt remain a source of pressure.';
 return {direction,label,reasons,meaning,uncertain,debtPressure,reserve};
}
function support(s){
 const deposits=s.active.filter(t=>t.account==='chequing'&&t.flow==='in'&&t.category==='Government benefits & support');
 return {deposits,total:deposits.reduce((n,t)=>n+t.amount,0),found:deposits.length>0};
}
function build(s,c){
 const matrix=Object.entries(s.totals).filter(([cat,n])=>n!==0&&actions[cat]).sort((a,b)=>b[1]-a[1]).map(([category,amount])=>({category,amount,monthly:amount/s.months,cells:actions[category],evidence:s.active.filter(t=>t.category===category&&!['Exclude','Transfer / card payment'].includes(t.category)).slice(0,4)}));
 const benefits=support(s);
 const recommendations=[];const add=(priority,title,evidence,action,verify,when)=>recommendations.push({priority,title,evidence,action,verify,when});
 add(benefits.found?3:2,benefits.found?'Review the support deposits already visible':'No government benefits or support deposits identified',benefits.found?`${benefits.deposits.length} categorized deposit(s), totaling ${benefits.total.toFixed(2)} CAD: ${benefits.deposits.slice(0,4).map(t=>t.description).join('; ')}.`:'No deposits categorized as government benefits, grants or income support appear in this chequing account during the selected dates.',benefits.found?'Check renewal requirements, payment changes and whether other support programs could address your needs. Budget only for support that is reliable.':'Make a benefits check part of your plan: review GST/HST credits, household/child benefits if relevant, provincial income or disability support, housing assistance, education grants and local subsidies. Use the Benefits Finder and check whether tax filing is required.', 'This describes the imported account and period. Unclear bank descriptions, other accounts, quarterly payments and non-cash support can be missed. You can correct a deposit to Government benefits & support in transaction review.','This week');
 if(s.unrecognized.length)add(0,'Resolve charges you do not recognize',`${s.unrecognized.length} transaction(s) marked not recognized.`, 'Check receipts and authorized household users. If still unfamiliar, contact the issuer through its official app or number and ask about dispute deadlines.','A merchant description cannot establish fraud.','Today');
 if(s.duplicates.length)add(0,'Check possible duplicate charges',`${s.duplicates.length} matching transaction group(s).`,'Compare bank statements and receipts. Exclude an import duplicate only after verifying it; dispute an actual erroneous charge through the issuer.','Repeated identical purchases can be legitimate.','Today');
 if(s.monthlySurplus<0)add(1,'Stop the spending deficit',`Monthly-equivalent spending exceeds confirmed income by ${(-s.monthlySurplus).toFixed(2)} CAD.`,'Protect housing, food, care and required payments. Review the largest categories and support options; make a realistic plan to close the gap.','Unclassified income and missing accounts can change this result.','This week');
 if((s.totals['Financing charges']||0)>0||c.debts.some(d=>d.balance>0&&d.rate>=c.threshold))add(1,'Review costly borrowing before committing surplus',`${(s.totals['Financing charges']||0).toFixed(2)} CAD in financing charges; debt details come from your inputs.`,'Verify balances/APRs and minimum payments. Compare an affordable repayment plan while preserving essential cash needs.','An interest charge does not reveal the loan balance or prove all borrowing is bad debt.','This week');
 for(const row of matrix){const title=row.category==='Health & care'?'Check medical-expense tax credits and reimbursement':row.category==='Giving'?'Check donation receipts and tax credits':'Review '+row.category.toLowerCase();add(row.category==='Health & care'?2:3,title,`${row.amount.toFixed(2)} CAD net in this category; ${row.evidence.map(t=>t.description).join('; ')}.`,row.cells.join(' '),row.category==='Health & care'?'For Canada, eligibility, the eligible period, family income thresholds and reimbursement exclusions matter. A CSV is not proof of an eligible expense. This may be a non-refundable tax credit, not a deduction or guaranteed refund.':row.category==='Giving'?'Verify the organization’s qualified status, receipt and applicable limits; no credit is assumed.':'Confirm classification, terms and actual savings before acting.',row.category==='Health & care'||row.category==='Giving'?'Before filing taxes':'This month');}
 const target=c.essentials===null?null:c.essentials*c.months,gap=target===null||c.reserve===null?null:Math.max(0,target-c.reserve);
 add(2,'Build an emergency system',gap===null?'Accessible reserve or essential budget is unknown.':`Reserve ${c.reserve.toFixed(2)} CAD; chosen target ${target.toFixed(2)} CAD; gap ${gap.toFixed(2)} CAD.`,gap===null?'Verify liquid savings after upcoming bills and the essential monthly budget.':gap>0?'Set a sustainable reserve contribution; also review reliable alternative cash flows, insurance and realistic social support.':'Maintain the reserve and review insurance, income stability and near-term obligations.', 'Credit limits and volatile investments are not equivalent to accessible cash.','This month');
 const unresolved=s.unknown.length||s.otherCredits||s.duplicates.length||s.unrecognized.length;
 const ready=gap===0&&c.essentials>0&&c.debtComplete&&c.stability==='stable'&&c.confirmedSurplus>0&&!unresolved&&!(s.totals['Financing charges']>0)&&!c.debts.some(d=>d.balance>0&&d.rate>=c.threshold)&&s.surplus>=0;
 const planning=gap===0&&c.essentials>0&&s.monthlySurplus>0;
 if(planning&&!ready)add(2,'Start an investment plan; finish the funding checks',`Observed monthly-equivalent surplus ${s.monthlySurplus.toFixed(2)} CAD and your entered reserve covers the chosen ${c.months}-month target.`, 'Start with goals and time horizons. Compare employer matching and appropriate registered accounts; review risk and fees. Before investing money, resolve costly debt, uncertain income, upcoming bills and incomplete transaction review. Confirm how much of this surplus repeats after irregular costs.', 'A planning opportunity is visible; an amount safe to invest is not yet verified. Keep the emergency reserve accessible.','This month');
 add(ready?2:4,ready?'Investigate investing your verified surplus':'Prepare for future growth',ready?`${c.confirmedSurplus.toFixed(2)} CAD entered as sustainable monthly surplus with the chosen reserve covered.`:'Investment readiness has not been established.',ready?'Review employer matching and suitable TFSA/RRSP, RESP or RDSP opportunities. Verify contribution room, eligibility, time horizon, risk tolerance and fees before choosing investments.':'Resolve transaction and debt questions, cover near-term obligations and build a reserve before deciding how much surplus can support long-term goals.','Two CSVs cannot determine suitability, tax position, account room or asset allocation.','After the immediate checks');
 return {benefits,matrix,recommendations:recommendations.sort((a,b)=>a.priority-b.priority),ready};
}
root.ResetGuidance={build,pillars,spiral,support};})(typeof window!=='undefined'?window:globalThis);
