(function(root){'use strict';
function build(s,c){const p=c.profile||{},rows=s.active.filter(t=>t.category!=='Exclude'),insights=[];
const add=(id,priority,title,evidence,action,verify,confidence)=>insights.push({id,priority,title,evidence,action,verify,confidence,when:'This week'});
const ccb=rows.filter(t=>t.account==='chequing'&&t.flow==='in'&&['Income','Government benefits & support'].includes(t.category)&&/\b(?:ccb|canada child benefit|child benefit)\b/i.test(t.description));
const disability=rows.filter(t=>t.account==='chequing'&&t.flow==='in'&&['Income','Government benefits & support'].includes(t.category)&&/\b(?:aish|odsp|disability benefit)\b/i.test(t.description));
if(disability.length)add('disability-support',2,'Review disability support, tax-credit and RDSP opportunities',`${disability.length} disability-support-like deposits appear.`, 'Confirm the program and your circumstances. Review renewal requirements, medical/disability records, possible Disability Tax Credit eligibility and RDSP opportunities where eligible.', 'A provincial support payment does not prove DTC or RDSP eligibility. Provincial income/asset rules may differ from federal benefit rules; check them before RRSP/TFSA changes.', 'Description-based signal; confirm');
const childcare=rows.filter(t=>t.flow==='out'&&t.category==='Childcare');
const family=p.children==='yes'||p.children!=='no'&&(ccb.length||childcare.length);
if(ccb.length)add('ccb-household',2,p.children==='no'?'Confirm the CCB household mismatch':'CCB suggests a household with children',`${ccb.length} CCB-like deposits: ${ccb.slice(0,3).map(t=>`${t.date} · ${t.description} · ${t.amount.toFixed(2)} CAD`).join('; ')}.`,p.children==='no'?'You selected no dependent children. Check whether these deposits belong to another household, relate to an earlier period or need recategorization. Child-related recommendations are suppressed until you confirm.':'Confirm your household details and check CCB records, childcare support and RESP education-saving opportunities. Check household income and benefit renewal requirements.', 'A deposit suggests child-related context; it does not establish the number or ages of children, custody or current eligibility.','Suggested by deposits; confirm');
else if(childcare.length&&p.children!=='no')add('childcare-household',2,'Childcare spending suggests family support checks',`${childcare.length} childcare-category purchases.`, 'Confirm whether these are your household’s dependent-care costs. Collect provider receipts and investigate applicable subsidies and childcare-expense deductions.','Spending may be for someone else. Receipt requirements, claimant rules and limits need checking.','Suggested by spending; confirm');
if(family)add('rrsp-family-benefits',2,'Review RRSP deductions alongside CCB and GST/HST',ccb.length?'CCB deposits and the book’s RRSP strategy suggest a family-income planning opportunity.':'Confirmed children or childcare spending suggest a family-income planning opportunity.','A claimed RRSP deduction may reduce adjusted family net income used for CCB and GST/HST credit calculations and may affect later benefit payments. Compare eligible deduction amounts, tax effects, benefit effects and cash-flow needs. Check employer matching and RESP grants where eligible.', `Use both partners’ relevant incomes, CRA contribution room, deduction timing and current benefit formulas. ${p.familyIncome===null||p.familyIncome===undefined?'Verified adjusted family net income is not provided.':`You entered ${p.familyIncome.toFixed(2)} CAD of adjusted family net income; verify the tax-year basis.`} A contribution is not automatically a deduction claimed that year; no optimum contribution or refund is inferred. Withdrawals generally affect taxable income. ${p.rrspRoom===null||p.rrspRoom===undefined?'RRSP room is unknown: verify your CRA records.':`You entered ${p.rrspRoom.toFixed(2)} CAD of room; verify it before contributing.`} Protect essentials, reserves and costly-debt repayments.`, 'Conditional planning opportunity');
const medical=rows.filter(t=>t.flow==='out'&&t.category==='Health & care');if(medical.length)add('medical-records',1,'Collect medical receipts and insurance records',`${medical.length} health/care charges totaling ${medical.reduce((n,t)=>n+t.amount,0).toFixed(2)} CAD before reimbursements. Examples: ${medical.slice(0,3).map(t=>t.description).join('; ')}.`,'Request itemized clinic/dental receipts and an annual pharmacy statement. Check eligible insurance reimbursement and claim deadlines first. Keep unreimbursed eligible expenses for a Canadian medical-expense tax-credit review; reconcile insurance payments and refunds.', 'Medical-expense relief is generally a tax credit, not an automatic refund. Eligibility, income thresholds, family claimant choices and the permitted expense period matter. Do not claim reimbursed costs twice.','Detected category; verify eligibility');
if(rows.some(t=>t.flow==='out'&&/\brrsp\b/i.test(t.description)))add('rrsp-records',2,'Reconcile RRSP contribution receipts', 'RRSP-labeled money-out transactions appear in the window.','Obtain contribution receipts, distinguish deposits from transfers between RRSPs and verify available room. Decide which eligible deductions to claim and which to carry forward.','A bank transaction does not prove deductibility. TFSA contributions do not generate the same deduction.','Description-based signal');
if(['self-employed','mixed'].includes(p.employment))add('self-employed',2,'Separate business records from household spending','You selected self-employment.','Separate eligible business expenses, invoices and receipts. Plan tax installments and applicable self-employed CPP; review GST/HST obligations and insurance.','Business-use proportions, registration rules and tax treatment require current records; not every purchase is deductible.','User-confirmed context');
if(p.employment==='employee'||rows.some(t=>t.account==='chequing'&&t.flow==='in'&&t.category==='Income'&&/payroll|salary|employer pay/i.test(t.description)))add('employer-benefits',3,'Check employer benefits and retirement matching','Employment income or employee context is present.','Review your benefits booklet for insurance reimbursement, pension/RRSP matching, disability coverage and training support. Ask HR about enrollment and matching deadlines.','A salary deposit does not prove a matching plan exists. Verify terms and affordability before changing contributions.','Employment signal; check plan terms');
if(p.province&&p.province!=='unknown')add('provincial-support',3,`Check ${p.province} support and coverage`,'You selected your province or territory.','Use the Benefits Finder and provincial official services to review housing, healthcare, disability, family, utility and training support relevant to your household.','Residence, household income and program-specific facts determine eligibility.','User-confirmed location');
const subs=new Map();rows.filter(t=>t.flow==='out'&&['Subscriptions','Utilities','Insurance'].includes(t.category)).forEach(t=>{const key=t.category+'|'+t.merchant;if(!subs.has(key))subs.set(key,[]);subs.get(key).push(t);});
for(const items of subs.values()){items.sort((a,b)=>a.date.localeCompare(b.date));const a=items[0],b=items.at(-1);if(a.date.slice(0,7)!==b.date.slice(0,7)&&b.amount>a.amount*1.15)add('price-rise-'+a.merchant.toLowerCase().replace(/[^a-z0-9]+/g,'-'),2,'Check a rising recurring bill',`${a.description}: ${a.amount.toFixed(2)} CAD on ${a.date}, then ${b.amount.toFixed(2)} CAD on ${b.date}.`,'Check whether a promotion expired, usage changed or a fee was added. Compare equivalent plans and ask the provider to explain the increase.','These may be different purchases; compare invoices before concluding a price increase.','Pattern candidate');}
if(p.goal&&p.goal!=='unknown')add('goal-plan',3,'Connect your next action to your goal',`Selected goal: ${p.goal}.`,'Set a goal amount and date. Separate near-term funds from long-term investment money and choose a sustainable contribution after essentials and debt obligations.','This goal does not determine the right investment or contribution amount.','User-confirmed goal');
return insights.sort((a,b)=>a.priority-b.priority);}
root.ResetIntelligence={build};})(typeof window!=='undefined'?window:globalThis);
