(function(root){'use strict';
const P=root.ResetPlanner,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cash=n=>n===null?'Unknown':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:2}).format(n);
let actions=new Map(),previous=null,current=null,currentRecommendations=[],loadSeq=0;
const names={monthlyIncome:'Monthly-equivalent income',monthlyExpenses:'Monthly-equivalent spending',monthlySurplus:'Monthly-equivalent surplus',financingMonthly:'Monthly-equivalent financing charges',reserve:'Entered accessible reserve',essentials:'Entered essential monthly budget',debtTotal:'Entered debt total (complete reviews only)'};
function render(report,recommendations){current=report;currentRecommendations=recommendations;const activeIds=new Set(recommendations.map(P.key));for(const [id,a] of actions){if(!activeIds.has(id)&&a.status==='todo'&&!a.due&&!a.notes&&a.impact===null)actions.delete(id);}for(const r of recommendations){const id=P.key(r);if(!actions.has(id))actions.set(id,{id,title:r.title,status:'todo',due:'',notes:'',impact:null});}
const snap=P.snapshot(report,[...actions.values()]);const overlap=previous&&previous.start<=snap.end&&snap.start<=previous.end;
const old=previous?`<h3>Compare with ${esc(previous.start)} to ${esc(previous.end)}</h3><p>${overlap?'The periods overlap. These changes do not represent an independent next-month comparison.':'Amounts describe the selected windows; changes do not prove that an action caused an improvement.'} Monthly equivalents normalize by period length. Account coverage, classification changes, seasonality and entered balances affect comparability.</p><div class="table-scroll"><table class="matrix"><thead><tr><th>Measure</th><th>Earlier</th><th>Now</th><th>Change</th></tr></thead><tbody>${P.compare(snap,previous).map(r=>`<tr><th>${names[r.key]}</th><td>${cash(r.before)}</td><td>${cash(r.now)}</td><td>${cash(r.change)}</td></tr>`).join('')}</tbody></table></div>`:'<p>To compare progress, download this plan and load it when reviewing your next period. The browser does not retain a financial history automatically.</p>';
function row(a,r){return `<article class="plan-action"><h3>${esc(a.title)}</h3>${r?`<p class="guidance-evidence">${esc(r.evidence)}</p><p>${esc(r.action)}</p><p class="report-note">${esc(r.verify)}</p>`:'<p class="report-note">Carried from an earlier report. Review whether this action still applies.</p>'}<div class="calculator-grid"><label class="field"><span class="field-label">Status</span><select data-plan="${a.id}" data-key="status"><option value="todo" ${a.status==='todo'?'selected':''}>To do</option><option value="doing" ${a.status==='doing'?'selected':''}>In progress</option><option value="done" ${a.status==='done'?'selected':''}>Done</option></select></label><label class="field"><span class="field-label">Review / due date</span><input data-plan="${a.id}" data-key="due" type="date" value="${esc(a.due)}"></label><label class="field"><span class="field-label">Your estimated monthly improvement (CAD)</span><input data-plan="${a.id}" data-key="impact" type="number" min="-1000000000" max="1000000000" step="any" value="${a.impact??''}" placeholder="Unknown — not automatically estimated"></label></div><label class="field"><span class="field-label">Next step / result / information to collect</span><textarea data-plan="${a.id}" data-key="notes" maxlength="1000">${esc(a.notes)}</textarea></label></article>`;}
const ids=new Set(recommendations.map(P.key)),first=recommendations.slice(0,6).map(r=>row(actions.get(P.key(r)),r)).join(''),rest=recommendations.slice(6).map(r=>row(actions.get(P.key(r)),r)).join(''),carried=[...actions.values()].filter(a=>!ids.has(a.id)).map(a=>row(a,null)).join('');
let section=document.getElementById('reset-plan');if(section)section.remove();section=document.createElement('section');section.className='activity-card';section.id='reset-plan';section.innerHTML=`<div class="eyebrow">Act → return → measure</div><h2>Your prioritized action plan</h2><p>Start with one or two actions. The first six are ordered by urgency and relevance. Each includes the observed evidence, a next step and checks to complete. Monthly improvements are your estimates, not guaranteed savings; avoid counting the same opportunity twice.</p><div id="plan-progress" role="status"></div>${first}${rest?`<details><summary>Other opportunities to review</summary>${rest}</details>`:''}${carried?`<details><summary>Actions carried from an earlier plan</summary>${carried}</details>`:''}<div class="actions"><button class="btn primary" id="save-plan">Download plan for next time</button></div><p class="report-note">This JSON file contains financial summaries, action notes and dates. Keep it private. It does not include raw transactions. Nothing is saved automatically.</p>${old}`;
document.querySelector('#report .spiral-summary').insertAdjacentElement('afterend',section);
function progress(){const all=[...actions.values()];document.getElementById('plan-progress').textContent=`${all.filter(a=>a.status==='done').length} of ${all.length} recorded actions marked done. Your entered expected monthly change totals ${cash(all.reduce((n,a)=>n+(a.impact||0),0))}; this is not measured savings.`;}
section.querySelectorAll('[data-plan]').forEach(el=>el.addEventListener('input',()=>{const a=actions.get(el.dataset.plan),key=el.dataset.key;if(key==='impact'){const n=el.value===''?null:Number(el.value);a[key]=n===null||Number.isFinite(n)&&Math.abs(n)<=1e9?n:null;}else a[key]=el.value;progress();}));
document.getElementById('save-plan').onclick=()=>{if(!document.getElementById('report-stale').hidden)return;const data=P.snapshot(current,[...actions.values()]);try{P.validate(data);}catch(e){document.getElementById('plan-progress').textContent=e.message;return;}const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=`financial-reset-plan-${report.end}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};progress();}
async function load(file){const seq=++loadSeq;if(!file)return;try{if(file.size>1024*1024)throw Error('Use a plan smaller than 1 MB.');const parsed=P.validate(JSON.parse(await file.text()));if(seq!==loadSeq)return;previous=parsed;for(const a of parsed.actions)actions.set(a.id,a);document.getElementById('plan-load-status').textContent=`Plan loaded for ${parsed.start} to ${parsed.end}; ${parsed.actions.length} action(s). Review it against the next complete period.`;if(current)render(current,currentRecommendations);}catch(e){if(seq!==loadSeq)return;document.getElementById('plan-load-status').textContent='Plan not loaded: '+e.message;}}
root.ResetPlanUI={render,load,reset(){loadSeq++;actions=new Map();previous=null;current=null;currentRecommendations=[];},text(){return [...actions.values()].map(a=>`${a.title}\nStatus: ${a.status}; review date: ${a.due||'Not set'}; estimated monthly change: ${cash(a.impact)}\n${a.notes}`).join('\n\n');}};
})(window);
